// <auto-generated />
using System;
using AgencySettlement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgencySettlement.Infrastructure.Migrations
{
    [DbContext(typeof(AgencySettlementDbContext))]
    [Migration("20260906093358_juan")]
    partial class juan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DetailCode")
                        .HasColumnType("int");

                    b.Property<int>("FreeQuotaCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.HasIndex("StateId");

                    b.ToTable("Agencies", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.EducationalLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StageTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageTypeId");

                    b.ToTable("EducationalLevels", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.ExamBooklet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EducationalLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "EducationalLevelId", "StudyFieldId");

                    b.ToTable("ExamBooklets", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.ExamMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExamModes", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.ExamPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ExamPhases", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.ExternalExamRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<long>("CandidateExamId")
                        .HasColumnType("bigint");

                    b.Property<int>("EducationalLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ExamModeId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PersianExecutionDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegistrationPlanId")
                        .HasColumnType("int");

                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateExamId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalExamRecords_CandidateExamId");

                    b.HasIndex("AgencyId", "YearId", "PersianExecutionDate")
                        .HasDatabaseName("IX_ExternalExamRecords_Agency_Year_Date");

                    b.HasIndex("RegistrationPlanId", "YearId", "PersianExecutionDate")
                        .HasDatabaseName("IX_ExternalExamRecords_ExamType_Year_Date");

                    b.ToTable("ExternalExamRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalExamRecords_CandidateExamId", "[CandidateExamId] > 0");
                        });
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Price", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("EducationalLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ExamModeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PersianExecutionDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RegistrationPlanId")
                        .HasColumnType("int");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "EducationalLevelId", "ExamModeId", "RegistrationPlanId", "YearId", "PersianExecutionDate", "IsActive")
                        .HasDatabaseName("IX_Prices_Match");

                    b.ToTable("Prices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prices_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.RegistrationPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationPlans", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Settlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "YearId")
                        .HasDatabaseName("IX_Settlements_Agency_Year");

                    b.ToTable("Settlements", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.SettlementHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("SettlementId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "CreatedAt")
                        .HasDatabaseName("IX_SettlementHistories_Agency_Date");

                    b.ToTable("SettlementHistories", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.SettlementItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AgencyAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("AgencyPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("EducationalLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ExamModeId")
                        .HasColumnType("int");

                    b.Property<int>("FreeCandidateCount")
                        .HasColumnType("int");

                    b.Property<decimal>("GajAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("GajPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("PaidCandidateCount")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationPlanId")
                        .HasColumnType("int");

                    b.Property<long>("SettlementId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("StudentAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("StudentPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "RegistrationPlanId", "StudyFieldId")
                        .HasDatabaseName("IX_SettlementItems_Settlement");

                    b.ToTable("SettlementItems", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.StageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StageTypes", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.StudyField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields", (string)null);
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.YearType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("YearTypes", (string)null);
                });

            modelBuilder.Entity("Percent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("AgencyPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("ExamModeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GajPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PersianExecutionDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("StudentPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "ExamModeId", "YearId", "PersianExecutionDate", "IsActive")
                        .HasDatabaseName("IX_Percent_Match");

                    b.ToTable("Percent", null, t =>
                        {
                            t.HasCheckConstraint("CK_Percent_AgencyPercent", "[AgencyPercent] >= 0 AND [AgencyPercent] <= 100");

                            t.HasCheckConstraint("CK_Percent_GajPercent", "[GajPercent] >= 0 AND [GajPercent] <= 100");

                            t.HasCheckConstraint("CK_Percent_StudentPercent", "[StudentPercent] >= 0 AND [StudentPercent] <= 100");

                            t.HasCheckConstraint("CK_Percent_Total", "[AgencyPercent] + [GajPercent] + [StudentPercent] = 100");
                        });
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Agency", b =>
                {
                    b.HasOne("AgencySettlement.Domain.Entities.Region", "Region")
                        .WithMany("Agencies")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgencySettlement.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("State");
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.EducationalLevel", b =>
                {
                    b.HasOne("AgencySettlement.Domain.Entities.StageType", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Region", b =>
                {
                    b.HasOne("AgencySettlement.Domain.Entities.State", "State")
                        .WithMany("Regions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.SettlementItem", b =>
                {
                    b.HasOne("AgencySettlement.Domain.Entities.Settlement", null)
                        .WithMany("Items")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Region", b =>
                {
                    b.Navigation("Agencies");
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.Settlement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AgencySettlement.Domain.Entities.State", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
